name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm test

  release:
    needs: test

    # don't run on forks
    if: ${{ github.repository_owner == 'SmartThingsCommunity' && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PI_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: smartthingspi
          GIT_AUTHOR_EMAIL: pi-team@smartthings.com
          GIT_COMMITTER_NAME: smartthingspi
          GIT_COMMITTER_EMAIL: pi-team@smartthings.com
        run: npx semantic-release
